PKG := "imuGAP"
VERSION := `Rscript -e "cat(read.dcf('DESCRIPTION')[,'Version'])"`
TARBALL := PKG + "_" + VERSION + ".tar.gz"

default: format lint docs test

[unix]
[doc('Clean up auxiliary files and directories')]
clean:
	rm -rf *.tar.gz *.Rcheck .Rproj.user src/*.o src/*.gcno src/*.gcda src/*.so src/*.dll figure figures doc Meta vignettes/*.html vignettes/*.pdf vignettes/figures/*.svg vignettes/figures/*.pdf vignettes/figures/*.png

[doc('Ensure local NAMESPACE exists (bootstrapped if missing)')]
bootstrap-namespace:
	#!/usr/bin/env Rscript
	if (!file.exists("NAMESPACE")) {
	  writeLines(c("# Generated by roxygen2: do not edit by hand", "useDynLib(imuGAP, .registration = TRUE)"), "NAMESPACE")
	}

[group('diagrams')]
[doc('Generate SVG and PDF diagrams from .mmd mermaid specifications')]
diagrams:
	#!/usr/bin/env bash
	set -euo pipefail
	if compgen -G "vignettes/figures/*.mmd" > /dev/null; then
		if command -v mmdc >/dev/null 2>&1; then
			CMD="mmdc"
		elif command -v npx >/dev/null 2>&1; then
			CMD="npx --yes -p @mermaid-js/mermaid-cli@11.17.0 mmdc"
		else
			missing=0
			for mmd in vignettes/figures/*.mmd; do
				[ -f "$mmd" ] || continue
				if [ ! -f "${mmd%.mmd}.svg" ] || [ ! -f "${mmd%.mmd}.pdf" ]; then
					missing=1
					break
				fi
			done
			if [ "$missing" -eq 1 ]; then
				echo "Error: Neither 'mmdc' nor 'npx' found and diagrams are missing; mermaid-cli is required." >&2
				exit 1
			else
				echo "Note: Neither 'mmdc' nor 'npx' found; keeping existing SVG/PDF diagrams."
				exit 0
			fi
		fi

		PUP_CFG=$(mktemp)
		echo '{"args": ["--no-sandbox", "--disable-setuid-sandbox"]}' > "$PUP_CFG"
		trap 'rm -f "$PUP_CFG"' EXIT

		for mmd in vignettes/figures/*.mmd; do
			[ -f "$mmd" ] || continue
			svg="${mmd%.mmd}.svg"
			pdf="${mmd%.mmd}.pdf"
			echo "Compiling $mmd -> $svg..."
			$CMD -p "$PUP_CFG" -i "$mmd" -o "$svg" -b transparent
			echo "Compiling $mmd -> $pdf..."
			$CMD -p "$PUP_CFG" -i "$mmd" -o "$pdf" -b transparent
		done
	fi

[doc('Regenerate roxygen output: man/*.Rd, NAMESPACE, and R/globals.R (all untracked)')]
docs: bootstrap-namespace diagrams
	#!/usr/bin/env Rscript
	if (requireNamespace("rstantools", quietly = TRUE)) rstantools::rstan_config()
	if (requireNamespace("Rcpp", quietly = TRUE)) Rcpp::compileAttributes()
	if (require(roxygen2)) roxygen2::roxygenize() else stop("missing 'roxygen2'")

[doc('Format R code using air')]
format:
	air format .

[doc('Check R code using air and lintr, and verify that Rcpp exports are up to date')]
lint: lintair lintr check-rcpp

[doc('Check that Rcpp export bindings in src/ are synchronized with Stan models')]
check-rcpp:
	#!/usr/bin/env bash
	set -euo pipefail
	Rscript -e "if (requireNamespace('rstantools', quietly = TRUE)) rstantools::rstan_config() else stop(\"missing 'rstantools'\"); if (requireNamespace('Rcpp', quietly = TRUE)) Rcpp::compileAttributes() else stop(\"missing 'Rcpp'\")"
	if [ -n "$(git status --porcelain -- src/RcppExports.cpp)" ]; then
		echo "Error: src/RcppExports.cpp is out of date. Run 'just docs' or 'Rcpp::compileAttributes()' and commit the changes." >&2
		git diff -- src/RcppExports.cpp 2>/dev/null || true
		exit 1
	fi

[doc('Check R code using air')]
lintair:
	air format . --check

[doc('Check R code using lintr')]
lintr: bootstrap-namespace
	#!/usr/bin/env Rscript
	if (require(lintr)) lintr::lint_package() else stop("missing 'lintr'")
	

[doc('Run unit tests using devtools')]
test: bootstrap-namespace
	#!/usr/bin/env Rscript 
	library(devtools)
	devtools::test()

[doc('Run unit tests using devtools (excluding dynamic Stan compilation by default), stopping on first failure')]
test-fast filter="": bootstrap-namespace
	#!/usr/bin/env Rscript
	library(devtools)
	filter_arg <- trimws("{{ filter }}")
	if (nzchar(filter_arg)) {
	  devtools::test(filter = filter_arg, stop_on_failure = TRUE)
	} else {
	  devtools::test(filter = "^stan-", invert = TRUE, stop_on_failure = TRUE)
	}

[doc('Check test coverage using covr')]
coverage: bootstrap-namespace
	#!/usr/bin/env Rscript
	if (require(covr)) print(covr::package_coverage()) else stop("missing 'covr'")

[doc('Check spelling across documentation and vignettes using spelling')]
spell: bootstrap-namespace
	#!/usr/bin/env Rscript
	if (require(spelling)) spelling::spell_check_package() else stop("missing 'spelling'")


[doc('Install development version of imuGAP')]
install: bootstrap-namespace docs
	R CMD INSTALL .

[doc('Remove development version of imuGAP')]
remove:
	R CMD REMOVE {{ PKG }}


[group('data')]
[doc('Regenerate all package data (inputs + all fitted artifacts; inputs need nc_measles)')]
data: data-inputs data-fit

[group('data')]
[doc('Regenerate the *_sim inputs from the simulation (requires the private nc_measles dataset)')]
data-inputs:
	Rscript data-raw/DATASET.R

[group('data')]
[doc('Regenerate core 3-layer fit artifacts (fit_sim, target_sim, predict_sim)')]
data-fit-main:
	Rscript data-raw/fit_data.R

[group('data')]
[doc('Regenerate 1-layer and 2-layer ablation fit artifacts')]
data-fit-layers:
	Rscript data-raw/fit_layers.R

[group('data')]
[doc('Run a single leave-school-out fold (by index=1..10 or school="name")')]
data-fit-school-fold index="1" school="":
	Rscript data-raw/fit_single_school_out.R {{ if index != "" { "--index " + index } else { "--school '" + school + "'" } }}

[group('data')]
[doc('Consolidate scratch fold files into data/leave_school_out_scruggs.rda')]
data-fit-school-consolidate:
	Rscript data-raw/consolidate_school_out.R

[group('data')]
[doc('Run all leave-school-out folds and consolidate into data/leave_school_out_scruggs.rda')]
data-fit-school-cv:
	#!/usr/bin/env bash
	set -euo pipefail
	for i in {1..10}; do
		just data-fit-school-fold "$i" &
	done
	wait
	just data-fit-school-consolidate

[group('data')]
[doc('Regenerate all fitted-data artifacts across all models')]
data-fit: data-fit-main data-fit-layers data-fit-school-cv


[doc('Build a tar.gz artifact')]
build: bootstrap-namespace diagrams docs
	R CMD build .

[doc('Check the built tar.gz artifact')]
check: build
	R CMD check {{ TARBALL }} --no-manual --no-tests

[doc('Check the built tar.gz artifact using CRAN settings')]
check-cran: build
	R CMD check {{ TARBALL }} --as-cran

[doc('Render vignettes to PDF and HTML locally')]
render: bootstrap-namespace diagrams
	#!/usr/bin/env Rscript
	if (!require(rmarkdown)) stop("missing 'rmarkdown'")
	if (require(devtools)) devtools::load_all(quiet = TRUE)
	files <- list.files("vignettes", pattern = "\\.Rmd$", full.names = TRUE)
	for (f in files) {
	  message("Rendering ", f, " to HTML...")
	  rmarkdown::render(f, output_format = "html_document", quiet = TRUE)
	  message("Rendering ", f, " to PDF...")
	  rmarkdown::render(f, output_format = "pdf_document", quiet = TRUE)
	}

[group('site')]
[doc('Fast build of pkgdown documentation site into docs/ (no package reinstallation)')]
site: bootstrap-namespace docs
	#!/usr/bin/env Rscript
	if (!requireNamespace("pkgdown", quietly = TRUE)) stop("missing 'pkgdown'")
	pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)

[group('site')]
[doc('Alias for just site (fast documentation build)')]
site-quick: site

[group('site')]
[doc('Full build of pkgdown site with package reinstallation so vignettes see updated data/code')]
site-full: bootstrap-namespace docs install
	#!/usr/bin/env Rscript
	if (!requireNamespace("pkgdown", quietly = TRUE)) stop("missing 'pkgdown'")
	pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)

[group('site')]
[doc('Preview pkgdown documentation on localhost; optionally specify a vignette/article item to re-render (e.g. just site-preview imuGAP)')]
site-preview item="" port="8000": bootstrap-namespace docs
	#!/usr/bin/env Rscript
	if (!requireNamespace("pkgdown", quietly = TRUE)) stop("missing 'pkgdown'")
	if (!requireNamespace("httpuv", quietly = TRUE)) stop("missing 'httpuv'")

	item <- trimws("{{ item }}")
	port_num <- as.integer("{{ port }}")
	url_path <- ""

	if (nzchar(item)) {
	  clean_item <- tools::file_path_sans_ext(basename(item))

	  if (identical(clean_item, "all")) {
	    message("Re-building entire pkgdown site...")
	    pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
	  } else if (identical(clean_item, "reference")) {
	    message("Re-building reference index and documentation...")
	    pkgdown::build_reference()
	    url_path <- "reference/index.html"
	  } else if (clean_item %in% c("home", "index", "readme")) {
	    message("Re-building home page...")
	    pkgdown::build_home()
	    url_path <- "index.html"
	  } else {
	    message(sprintf("Targeted build for article '%s'...", clean_item))
	    pkgdown::build_article(clean_item)
	    url_path <- sprintf("articles/%s.html", clean_item)
	  }
	} else {
	  message("Re-building entire pkgdown site...")
	  pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
	}

	target_url <- sprintf("http://127.0.0.1:%d/%s", port_num, url_path)
	message(sprintf("Serving pkgdown site at %s (Ctrl+C to stop)", target_url))
	httpuv::runStaticServer(
	  dir = "docs",
	  host = "127.0.0.1",
	  port = port_num,
	  browse = interactive() || nzchar(Sys.getenv("BROWSER"))
	)



