// Generated by rstantools.  Do not edit by hand.

/*
    imuGAP is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    imuGAP is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with imuGAP.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_impute_school_coverage_process_stateonly_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 136> locations_array__ =
  {" (found before start of program)",
  " (in 'impute_school_coverage_process_stateonly', line 161, column 2 to column 23)",
  " (in 'impute_school_coverage_process_stateonly', line 168, column 2 to column 29)",
  " (in 'impute_school_coverage_process_stateonly', line 177, column 0 to column 43)",
  " (in 'impute_school_coverage_process_stateonly', line 189, column 2 to column 49)",
  " (in 'impute_school_coverage_process_stateonly', line 192, column 2 to column 129)",
  " (in 'impute_school_coverage_process_stateonly', line 196, column 2 to column 116)",
  " (in 'impute_school_coverage_process_stateonly', line 199, column 2 to column 39)",
  " (in 'impute_school_coverage_process_stateonly', line 205, column 4 to column 68)",
  " (in 'impute_school_coverage_process_stateonly', line 204, column 25 to line 206, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 204, column 2 to line 206, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 213, column 4 to column 28)",
  " (in 'impute_school_coverage_process_stateonly', line 219, column 4 to column 35)",
  " (in 'impute_school_coverage_process_stateonly', line 227, column 4 to column 35)",
  " (in 'impute_school_coverage_process_stateonly', line 209, column 21 to line 228, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 209, column 2 to line 228, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 103, column 2 to column 20)",
  " (in 'impute_school_coverage_process_stateonly', line 104, column 2 to column 24)",
  " (in 'impute_school_coverage_process_stateonly', line 107, column 2 to column 23)",
  " (in 'impute_school_coverage_process_stateonly', line 108, column 27 to column 31)",
  " (in 'impute_school_coverage_process_stateonly', line 108, column 33 to column 40)",
  " (in 'impute_school_coverage_process_stateonly', line 108, column 2 to column 53)",
  " (in 'impute_school_coverage_process_stateonly', line 112, column 2 to column 21)",
  " (in 'impute_school_coverage_process_stateonly', line 113, column 21 to column 26)",
  " (in 'impute_school_coverage_process_stateonly', line 113, column 2 to column 28)",
  " (in 'impute_school_coverage_process_stateonly', line 114, column 21 to column 26)",
  " (in 'impute_school_coverage_process_stateonly', line 114, column 2 to column 28)",
  " (in 'impute_school_coverage_process_stateonly', line 118, column 2 to column 29)",
  " (in 'impute_school_coverage_process_stateonly', line 119, column 8 to column 13)",
  " (in 'impute_school_coverage_process_stateonly', line 119, column 2 to column 67)",
  " (in 'impute_school_coverage_process_stateonly', line 121, column 45 to column 54)",
  " (in 'impute_school_coverage_process_stateonly', line 121, column 2 to column 56)",
  " (in 'impute_school_coverage_process_stateonly', line 122, column 44 to column 53)",
  " (in 'impute_school_coverage_process_stateonly', line 122, column 2 to column 55)",
  " (in 'impute_school_coverage_process_stateonly', line 123, column 42 to column 51)",
  " (in 'impute_school_coverage_process_stateonly', line 123, column 2 to column 53)",
  " (in 'impute_school_coverage_process_stateonly', line 125, column 26 to column 35)",
  " (in 'impute_school_coverage_process_stateonly', line 125, column 2 to column 45)",
  " (in 'impute_school_coverage_process_stateonly', line 128, column 2 to column 37)",
  " (in 'impute_school_coverage_process_stateonly', line 134, column 2 to column 11)",
  " (in 'impute_school_coverage_process_stateonly', line 135, column 9 to column 17)",
  " (in 'impute_school_coverage_process_stateonly', line 135, column 19 to column 23)",
  " (in 'impute_school_coverage_process_stateonly', line 135, column 2 to column 28)",
  " (in 'impute_school_coverage_process_stateonly', line 140, column 11 to column 16)",
  " (in 'impute_school_coverage_process_stateonly', line 140, column 2 to column 82)",
  " (in 'impute_school_coverage_process_stateonly', line 142, column 26 to column 35)",
  " (in 'impute_school_coverage_process_stateonly', line 142, column 2 to column 37)",
  " (in 'impute_school_coverage_process_stateonly', line 143, column 26 to column 35)",
  " (in 'impute_school_coverage_process_stateonly', line 143, column 2 to column 37)",
  " (in 'impute_school_coverage_process_stateonly', line 148, column 4 to column 52)",
  " (in 'impute_school_coverage_process_stateonly', line 150, column 4 to column 93)",
  " (in 'impute_school_coverage_process_stateonly', line 146, column 32 to line 151, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 146, column 2 to line 151, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 156, column 0 to column 23)",
  " (in 'impute_school_coverage_process_stateonly', line 161, column 9 to column 13)",
  " (in 'impute_school_coverage_process_stateonly', line 168, column 9 to column 16)",
  " (in 'impute_school_coverage_process_stateonly', line 177, column 7 to column 15)",
  " (in 'impute_school_coverage_process_stateonly', line 189, column 9 to column 17)",
  " (in 'impute_school_coverage_process_stateonly', line 192, column 27 to column 41)",
  " (in 'impute_school_coverage_process_stateonly', line 196, column 26 to column 35)",
  " (in 'impute_school_coverage_process_stateonly', line 199, column 26 to column 31)",
  " (in 'impute_school_coverage_process_stateonly', line 7, column 4 to column 35)",
  " (in 'impute_school_coverage_process_stateonly', line 9, column 8 to column 92)",
  " (in 'impute_school_coverage_process_stateonly', line 8, column 34 to line 10, column 5)",
  " (in 'impute_school_coverage_process_stateonly', line 8, column 4 to line 10, column 5)",
  " (in 'impute_school_coverage_process_stateonly', line 11, column 10 to column 21)",
  " (in 'impute_school_coverage_process_stateonly', line 11, column 4 to column 34)",
  " (in 'impute_school_coverage_process_stateonly', line 13, column 8 to column 36)",
  " (in 'impute_school_coverage_process_stateonly', line 12, column 35 to line 14, column 5)",
  " (in 'impute_school_coverage_process_stateonly', line 12, column 4 to line 14, column 5)",
  " (in 'impute_school_coverage_process_stateonly', line 15, column 4 to column 29)",
  " (in 'impute_school_coverage_process_stateonly', line 16, column 4 to column 30)",
  " (in 'impute_school_coverage_process_stateonly', line 6, column 59 to line 17, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 21, column 4 to column 47)",
  " (in 'impute_school_coverage_process_stateonly', line 22, column 11 to column 16)",
  " (in 'impute_school_coverage_process_stateonly', line 22, column 18 to column 23)",
  " (in 'impute_school_coverage_process_stateonly', line 22, column 4 to column 32)",
  " (in 'impute_school_coverage_process_stateonly', line 24, column 8 to column 36)",
  " (in 'impute_school_coverage_process_stateonly', line 23, column 23 to line 25, column 5)",
  " (in 'impute_school_coverage_process_stateonly', line 23, column 4 to line 25, column 5)",
  " (in 'impute_school_coverage_process_stateonly', line 26, column 4 to column 18)",
  " (in 'impute_school_coverage_process_stateonly', line 20, column 59 to line 27, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 31, column 4 to column 23)",
  " (in 'impute_school_coverage_process_stateonly', line 32, column 4 to column 34)",
  " (in 'impute_school_coverage_process_stateonly', line 30, column 26 to line 33, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 36, column 4 to column 23)",
  " (in 'impute_school_coverage_process_stateonly', line 37, column 4 to column 34)",
  " (in 'impute_school_coverage_process_stateonly', line 35, column 34 to line 38, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 41, column 4 to column 26)",
  " (in 'impute_school_coverage_process_stateonly', line 42, column 15 to column 20)",
  " (in 'impute_school_coverage_process_stateonly', line 42, column 4 to column 26)",
  " (in 'impute_school_coverage_process_stateonly', line 44, column 8 to column 31)",
  " (in 'impute_school_coverage_process_stateonly', line 43, column 23 to line 45, column 5)",
  " (in 'impute_school_coverage_process_stateonly', line 43, column 4 to line 45, column 5)",
  " (in 'impute_school_coverage_process_stateonly', line 46, column 4 to column 15)",
  " (in 'impute_school_coverage_process_stateonly', line 40, column 32 to line 47, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 50, column 4 to column 26)",
  " (in 'impute_school_coverage_process_stateonly', line 51, column 11 to column 16)",
  " (in 'impute_school_coverage_process_stateonly', line 51, column 4 to column 22)",
  " (in 'impute_school_coverage_process_stateonly', line 53, column 8 to column 31)",
  " (in 'impute_school_coverage_process_stateonly', line 52, column 23 to line 54, column 5)",
  " (in 'impute_school_coverage_process_stateonly', line 52, column 4 to line 54, column 5)",
  " (in 'impute_school_coverage_process_stateonly', line 55, column 4 to column 15)",
  " (in 'impute_school_coverage_process_stateonly', line 49, column 28 to line 56, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 62, column 9 to column 16)",
  " (in 'impute_school_coverage_process_stateonly', line 62, column 2 to column 43)",
  " (in 'impute_school_coverage_process_stateonly', line 65, column 9 to column 13)",
  " (in 'impute_school_coverage_process_stateonly', line 65, column 15 to column 22)",
  " (in 'impute_school_coverage_process_stateonly', line 65, column 2 to column 48)",
  " (in 'impute_school_coverage_process_stateonly', line 66, column 9 to column 16)",
  " (in 'impute_school_coverage_process_stateonly', line 66, column 2 to column 22)",
  " (in 'impute_school_coverage_process_stateonly', line 69, column 4 to column 80)",
  " (in 'impute_school_coverage_process_stateonly', line 70, column 4 to column 38)",
  " (in 'impute_school_coverage_process_stateonly', line 71, column 4 to column 36)",
  " (in 'impute_school_coverage_process_stateonly', line 72, column 4 to column 41)",
  " (in 'impute_school_coverage_process_stateonly', line 73, column 4 to column 84)",
  " (in 'impute_school_coverage_process_stateonly', line 68, column 26 to line 74, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 68, column 2 to line 74, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 76, column 9 to column 13)",
  " (in 'impute_school_coverage_process_stateonly', line 76, column 15 to column 22)",
  " (in 'impute_school_coverage_process_stateonly', line 76, column 2 to column 92)",
  " (in 'impute_school_coverage_process_stateonly', line 77, column 2 to column 38)",
  " (in 'impute_school_coverage_process_stateonly', line 78, column 2 to column 38)",
  " (in 'impute_school_coverage_process_stateonly', line 81, column 4 to column 29)",
  " (in 'impute_school_coverage_process_stateonly', line 84, column 43 to column 49)",
  " (in 'impute_school_coverage_process_stateonly', line 84, column 6 to column 49)",
  " (in 'impute_school_coverage_process_stateonly', line 85, column 6 to column 112)",
  " (in 'impute_school_coverage_process_stateonly', line 83, column 23 to line 86, column 5)",
  " (in 'impute_school_coverage_process_stateonly', line 83, column 4 to line 86, column 5)",
  " (in 'impute_school_coverage_process_stateonly', line 87, column 4 to column 74)",
  " (in 'impute_school_coverage_process_stateonly', line 80, column 26 to line 88, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 80, column 2 to line 88, column 3)",
  " (in 'impute_school_coverage_process_stateonly', line 91, column 9 to column 23)",
  " (in 'impute_school_coverage_process_stateonly', line 91, column 2 to column 74)",
  " (in 'impute_school_coverage_process_stateonly', line 92, column 2 to column 27)",
  " (in 'impute_school_coverage_process_stateonly', line 59, column 98 to line 93, column 1)"};
std::vector<std::vector<int>>
bounds_to_range(const std::vector<int>& lowers, const int& ub, std::ostream*
                pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_row_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>,
                stan::base_type_t<T1__>>,-1,-1>
element_mult_expand(const T0__& colv_arg__, const T1__& rowv_arg__,
                    std::ostream* pstream__);
template <typename T0__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,-1,1>
diff(const T0__& obj_arg__, std::ostream* pstream__);
template <typename T0__,
          stan::require_all_t<stan::is_row_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,1,-1>
diff(const T0__& obj_arg__, std::ostream* pstream__);
template <typename T0__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T0__>,
                              stan::is_vt_not_complex<T0__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,1,-1>
colsum(const T0__& obj_arg__, std::ostream* pstream__);
template <typename T0__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T0__>,
                              stan::is_vt_not_complex<T0__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,-1,1>
rowsum(const T0__& obj_arg__, std::ostream* pstream__);
template <typename T2__, typename T3__, typename T4__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_stan_scalar<T4__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T2__>,
                stan::base_type_t<T3__>, T4__>,-1,1>
unrolled_dose(const int& n_yr, const int& n_doses, const T2__&
              dose_sched_arg__, const T3__& lambda_raw_arg__, const T4__&
              epsilon_p, std::ostream* pstream__);
std::vector<std::vector<int>>
bounds_to_range(const std::vector<int>& lowers, const int& ub, std::ostream*
                pstream__) {
  using local_scalar_t__ = double;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int size_bounds = std::numeric_limits<int>::min();
    current_statement__ = 61;
    size_bounds = stan::math::size(lowers);
    current_statement__ = 64;
    if (stan::math::logical_gt(
          stan::model::rvalue(lowers, "lowers",
            stan::model::index_uni(size_bounds)), ub)) {
      current_statement__ = 62;
      if (pstream__) {
        stan::math::stan_print(pstream__, "Upper bound, ");
        stan::math::stan_print(pstream__, ub);
        stan::math::stan_print(pstream__, " is less than last lower bound, ");
        stan::math::stan_print(pstream__,
          stan::model::rvalue(lowers, "lowers",
            stan::model::index_uni(size_bounds)));
        *(pstream__) << std::endl;
      }
    }
    current_statement__ = 65;
    stan::math::validate_non_negative_index("uppers", "size_bounds",
      size_bounds);
    std::vector<int> uppers =
      std::vector<int>(size_bounds, std::numeric_limits<int>::min());
    current_statement__ = 69;
    for (int i = 1; i <= (size_bounds - 1); ++i) {
      current_statement__ = 67;
      stan::model::assign(uppers,
        (stan::model::rvalue(lowers, "lowers",
           stan::model::index_uni((i + 1))) - 1),
        "assigning variable uppers", stan::model::index_uni(i));
    }
    current_statement__ = 70;
    stan::model::assign(uppers, ub, "assigning variable uppers",
      stan::model::index_uni(size_bounds));
    current_statement__ = 71;
    return std::vector<std::vector<int>>{lowers, uppers};
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_row_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>,
                stan::base_type_t<T1__>>,-1,-1>
element_mult_expand(const T0__& colv_arg__, const T1__& rowv_arg__,
                    std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             stan::base_type_t<T1__>>;
  int current_statement__ = 0;
  const auto& colv = stan::math::to_ref(colv_arg__);
  const auto& rowv = stan::math::to_ref(rowv_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int nrows = std::numeric_limits<int>::min();
    current_statement__ = 73;
    nrows = stan::math::size(colv);
    int ncols = std::numeric_limits<int>::min();
    current_statement__ = 73;
    ncols = stan::math::size(rowv);
    current_statement__ = 74;
    stan::math::validate_non_negative_index("result", "nrows", nrows);
    current_statement__ = 75;
    stan::math::validate_non_negative_index("result", "ncols", ncols);
    Eigen::Matrix<local_scalar_t__,-1,-1> result =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(nrows, ncols,
        DUMMY_VAR__);
    current_statement__ = 79;
    for (int i = 1; i <= nrows; ++i) {
      current_statement__ = 77;
      stan::model::assign(result,
        stan::math::multiply(rowv,
          stan::model::rvalue(colv, "colv", stan::model::index_uni(i))),
        "assigning variable result", stan::model::index_uni(i),
        stan::model::index_omni());
    }
    current_statement__ = 80;
    return result;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,-1,1>
diff(const T0__& obj_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  const auto& obj = stan::math::to_ref(obj_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int sz = std::numeric_limits<int>::min();
    current_statement__ = 82;
    sz = stan::math::size(obj);
    current_statement__ = 83;
    return stan::math::subtract(
             stan::model::rvalue(obj, "obj", stan::model::index_min(2)),
             stan::model::rvalue(obj, "obj",
               stan::model::index_min_max(1, (sz - 1))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__,
          stan::require_all_t<stan::is_row_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,1,-1>
diff(const T0__& obj_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  const auto& obj = stan::math::to_ref(obj_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int sz = std::numeric_limits<int>::min();
    current_statement__ = 85;
    sz = stan::math::size(obj);
    current_statement__ = 86;
    return stan::math::subtract(
             stan::model::rvalue(obj, "obj", stan::model::index_min(2)),
             stan::model::rvalue(obj, "obj",
               stan::model::index_min_max(1, (sz - 1))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T0__>,
                              stan::is_vt_not_complex<T0__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,1,-1>
colsum(const T0__& obj_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  const auto& obj = stan::math::to_ref(obj_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int ncols = std::numeric_limits<int>::min();
    current_statement__ = 88;
    ncols = stan::math::cols(obj);
    current_statement__ = 89;
    stan::math::validate_non_negative_index("res", "ncols", ncols);
    Eigen::Matrix<local_scalar_t__,1,-1> res =
      Eigen::Matrix<local_scalar_t__,1,-1>::Constant(ncols, DUMMY_VAR__);
    current_statement__ = 93;
    for (int i = 1; i <= ncols; ++i) {
      current_statement__ = 91;
      stan::model::assign(res,
        stan::math::sum(
          stan::model::rvalue(obj, "obj", stan::model::index_omni(),
            stan::model::index_uni(i))), "assigning variable res",
        stan::model::index_uni(i));
    }
    current_statement__ = 94;
    return res;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T0__>,
                              stan::is_vt_not_complex<T0__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,-1,1>
rowsum(const T0__& obj_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  const auto& obj = stan::math::to_ref(obj_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int nrows = std::numeric_limits<int>::min();
    current_statement__ = 96;
    nrows = stan::math::cols(obj);
    current_statement__ = 97;
    stan::math::validate_non_negative_index("res", "nrows", nrows);
    Eigen::Matrix<local_scalar_t__,-1,1> res =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nrows, DUMMY_VAR__);
    current_statement__ = 101;
    for (int i = 1; i <= nrows; ++i) {
      current_statement__ = 99;
      stan::model::assign(res,
        stan::math::sum(
          stan::model::rvalue(obj, "obj", stan::model::index_uni(i),
            stan::model::index_omni())), "assigning variable res",
        stan::model::index_uni(i));
    }
    current_statement__ = 102;
    return res;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T2__, typename T3__, typename T4__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_stan_scalar<T4__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T2__>,
                stan::base_type_t<T3__>, T4__>,-1,1>
unrolled_dose(const int& n_yr, const int& n_doses, const T2__&
              dose_sched_arg__, const T3__& lambda_raw_arg__, const T4__&
              epsilon_p, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T2__>,
                             stan::base_type_t<T3__>, T4__>;
  int current_statement__ = 0;
  const auto& dose_sched = stan::math::to_ref(dose_sched_arg__);
  const auto& lambda_raw = stan::math::to_ref(lambda_raw_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 104;
    stan::math::validate_non_negative_index("lambda", "n_doses", n_doses);
    Eigen::Matrix<local_scalar_t__,-1,1> lambda =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_doses, DUMMY_VAR__);
    current_statement__ = 105;
    stan::model::assign(lambda, stan::math::exp(lambda_raw),
      "assigning variable lambda");
    current_statement__ = 106;
    stan::math::validate_non_negative_index("dXcdf", "n_yr", n_yr);
    current_statement__ = 107;
    stan::math::validate_non_negative_index("dXcdf", "n_doses", n_doses);
    Eigen::Matrix<local_scalar_t__,-1,-1> dXcdf =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n_yr, n_doses,
        DUMMY_VAR__);
    current_statement__ = 106;
    stan::math::validate_non_negative_index("dXpdf", "n_yr", n_yr);
    current_statement__ = 107;
    stan::math::validate_non_negative_index("dXpdf", "n_doses", n_doses);
    Eigen::Matrix<local_scalar_t__,-1,-1> dXpdf =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n_yr, n_doses,
        DUMMY_VAR__);
    current_statement__ = 106;
    stan::math::validate_non_negative_index("normdXpdf", "n_yr", n_yr);
    current_statement__ = 107;
    stan::math::validate_non_negative_index("normdXpdf", "n_doses", n_doses);
    Eigen::Matrix<local_scalar_t__,-1,-1> normdXpdf =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n_yr, n_doses,
        DUMMY_VAR__);
    current_statement__ = 109;
    stan::math::validate_non_negative_index("rem", "n_doses", n_doses);
    Eigen::Matrix<local_scalar_t__,-1,1> rem =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_doses, DUMMY_VAR__);
    current_statement__ = 117;
    for (int dose = 1; dose <= n_doses; ++dose) {
      current_statement__ = 111;
      stan::model::assign(dXcdf,
        stan::math::subtract(1,
          stan::math::exp(
            stan::math::minus(
              stan::math::cumulative_sum(
                stan::math::multiply(
                  stan::model::rvalue(dose_sched, "dose_sched",
                    stan::model::index_omni(), stan::model::index_uni(dose)),
                  stan::model::rvalue(lambda, "lambda",
                    stan::model::index_uni(dose))))))),
        "assigning variable dXcdf", stan::model::index_omni(),
        stan::model::index_uni(dose));
      current_statement__ = 112;
      stan::model::assign(rem, (1 -
        stan::model::rvalue(dXcdf, "dXcdf", stan::model::index_uni(n_yr),
          stan::model::index_uni(dose))), "assigning variable rem",
        stan::model::index_uni(dose));
      current_statement__ = 113;
      stan::model::assign(dXpdf,
        stan::model::rvalue(dXcdf, "dXcdf", stan::model::index_uni(1),
          stan::model::index_uni(dose)), "assigning variable dXpdf",
        stan::model::index_uni(1), stan::model::index_uni(dose));
      current_statement__ = 114;
      stan::model::assign(dXpdf,
        diff(
          stan::model::rvalue(dXcdf, "dXcdf", stan::model::index_omni(),
            stan::model::index_uni(dose)), pstream__),
        "assigning variable dXpdf", stan::model::index_min(2),
        stan::model::index_uni(dose));
      current_statement__ = 115;
      stan::model::assign(normdXpdf,
        stan::math::add(
          stan::math::reverse(
            stan::math::cumulative_sum(
              stan::math::reverse(
                stan::model::rvalue(dXpdf, "dXpdf",
                  stan::model::index_omni(), stan::model::index_uni(dose))))),
          stan::model::rvalue(rem, "rem", stan::model::index_uni(dose))),
        "assigning variable normdXpdf", stan::model::index_omni(),
        stan::model::index_uni(dose));
    }
    current_statement__ = 118;
    stan::math::validate_non_negative_index("conditional_dXpdf", "n_yr", n_yr);
    current_statement__ = 119;
    stan::math::validate_non_negative_index("conditional_dXpdf", "n_doses",
      n_doses);
    Eigen::Matrix<local_scalar_t__,-1,-1> conditional_dXpdf =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n_yr, n_doses,
        DUMMY_VAR__);
    current_statement__ = 120;
    stan::model::assign(conditional_dXpdf,
      stan::math::rep_matrix(0, n_yr, n_doses),
      "assigning variable conditional_dXpdf");
    current_statement__ = 118;
    stan::math::validate_non_negative_index("conditional_dXcdf", "n_yr", n_yr);
    current_statement__ = 119;
    stan::math::validate_non_negative_index("conditional_dXcdf", "n_doses",
      n_doses);
    Eigen::Matrix<local_scalar_t__,-1,-1> conditional_dXcdf =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n_yr, n_doses,
        DUMMY_VAR__);
    current_statement__ = 121;
    stan::model::assign(conditional_dXpdf,
      stan::model::rvalue(dXpdf, "dXpdf", stan::model::index_omni(),
        stan::model::index_uni(1)), "assigning variable conditional_dXpdf",
      stan::model::index_omni(), stan::model::index_uni(1));
    current_statement__ = 122;
    stan::model::assign(conditional_dXcdf,
      stan::model::rvalue(dXcdf, "dXcdf", stan::model::index_omni(),
        stan::model::index_uni(1)), "assigning variable conditional_dXcdf",
      stan::model::index_omni(), stan::model::index_uni(1));
    current_statement__ = 131;
    for (int dose = 2; dose <= n_doses; ++dose) {
      int prev_dose = std::numeric_limits<int>::min();
      current_statement__ = 123;
      prev_dose = (dose - 1);
      current_statement__ = 128;
      for (int ly = 1; ly <= n_yr; ++ly) {
        current_statement__ = 125;
        if (stan::math::logical_lt(
              stan::model::rvalue(normdXpdf, "normdXpdf",
                stan::model::index_uni(ly), stan::model::index_uni(dose)),
              epsilon_p)) {
          break;
        }
        current_statement__ = 126;
        stan::model::assign(conditional_dXpdf,
          stan::math::add(
            stan::model::deep_copy(
              stan::model::rvalue(conditional_dXpdf, "conditional_dXpdf",
                stan::model::index_min(ly), stan::model::index_uni(dose))),
            stan::math::divide(
              stan::math::multiply(
                stan::model::rvalue(conditional_dXpdf, "conditional_dXpdf",
                  stan::model::index_uni(ly),
                  stan::model::index_uni(prev_dose)),
                stan::model::rvalue(dXpdf, "dXpdf",
                  stan::model::index_min(ly), stan::model::index_uni(dose))),
              stan::model::rvalue(normdXpdf, "normdXpdf",
                stan::model::index_uni(ly), stan::model::index_uni(dose)))),
          "assigning variable conditional_dXpdf", stan::model::index_min(ly),
          stan::model::index_uni(dose));
      }
      current_statement__ = 129;
      stan::model::assign(conditional_dXcdf,
        stan::math::cumulative_sum(
          stan::model::rvalue(conditional_dXpdf, "conditional_dXpdf",
            stan::model::index_omni(), stan::model::index_uni(dose))),
        "assigning variable conditional_dXcdf", stan::model::index_omni(),
        stan::model::index_uni(dose));
    }
    current_statement__ = 132;
    stan::math::validate_non_negative_index("unrolled_dose_cdf",
      "n_doses * n_yr", (n_doses * n_yr));
    Eigen::Matrix<local_scalar_t__,-1,1> unrolled_dose_cdf =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant((n_doses * n_yr),
        DUMMY_VAR__);
    current_statement__ = 133;
    stan::model::assign(unrolled_dose_cdf,
      stan::math::to_vector(conditional_dXcdf),
      "assigning variable unrolled_dose_cdf");
    current_statement__ = 134;
    return unrolled_dose_cdf;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_impute_school_coverage_process_stateonly final : public model_base_crtp<model_impute_school_coverage_process_stateonly> {
private:
  int n_yr;
  int n_cohort;
  int n_doses;
  Eigen::Matrix<double,-1,-1> dose_sched_data__;
  int n_obs;
  std::vector<int> y_obs;
  std::vector<int> y_smp;
  int n_weights;
  std::vector<int> obs_to_weights_bounds;
  std::vector<int> weights_cohort;
  std::vector<int> weights_life_year;
  std::vector<int> weights_dose;
  Eigen::Matrix<double,-1,1> weights_data__;
  int predict_mode;
  int k_bs;
  Eigen::Matrix<double,-1,-1> bs_data__;
  std::vector<std::vector<int>> obs_map;
  std::vector<int> phi_lookup;
  std::vector<int> cdf_lookup;
  double epsilon_p;
  int unrolled_dose_probs_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> dose_sched{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> weights{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> bs{nullptr, 0, 0};
public:
  ~model_impute_school_coverage_process_stateonly() {}
  model_impute_school_coverage_process_stateonly(stan::io::var_context&
                                                 context__, unsigned int
                                                 random_seed__ = 0,
                                                 std::ostream*
                                                 pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_impute_school_coverage_process_stateonly_namespace::model_impute_school_coverage_process_stateonly";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 16;
      context__.validate_dims("data initialization", "n_yr", "int",
        std::vector<size_t>{});
      n_yr = std::numeric_limits<int>::min();
      current_statement__ = 16;
      n_yr = context__.vals_i("n_yr")[(1 - 1)];
      current_statement__ = 16;
      stan::math::check_greater_or_equal(function__, "n_yr", n_yr, 1);
      current_statement__ = 17;
      context__.validate_dims("data initialization", "n_cohort", "int",
        std::vector<size_t>{});
      n_cohort = std::numeric_limits<int>::min();
      current_statement__ = 17;
      n_cohort = context__.vals_i("n_cohort")[(1 - 1)];
      current_statement__ = 17;
      stan::math::check_greater_or_equal(function__, "n_cohort", n_cohort, 1);
      current_statement__ = 18;
      context__.validate_dims("data initialization", "n_doses", "int",
        std::vector<size_t>{});
      n_doses = std::numeric_limits<int>::min();
      current_statement__ = 18;
      n_doses = context__.vals_i("n_doses")[(1 - 1)];
      current_statement__ = 18;
      stan::math::check_greater_or_equal(function__, "n_doses", n_doses, 1);
      current_statement__ = 19;
      stan::math::validate_non_negative_index("dose_sched", "n_yr", n_yr);
      current_statement__ = 20;
      stan::math::validate_non_negative_index("dose_sched", "n_doses",
        n_doses);
      current_statement__ = 21;
      context__.validate_dims("data initialization", "dose_sched", "double",
        std::vector<size_t>{static_cast<size_t>(n_yr),
          static_cast<size_t>(n_doses)});
      dose_sched_data__ = Eigen::Matrix<double,-1,-1>::Constant(n_yr,
                            n_doses,
                            std::numeric_limits<double>::quiet_NaN());
      new (&dose_sched)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(dose_sched_data__.data(),
        n_yr, n_doses);
      {
        std::vector<local_scalar_t__> dose_sched_flat__;
        current_statement__ = 21;
        dose_sched_flat__ = context__.vals_r("dose_sched");
        current_statement__ = 21;
        pos__ = 1;
        current_statement__ = 21;
        for (int sym1__ = 1; sym1__ <= n_doses; ++sym1__) {
          current_statement__ = 21;
          for (int sym2__ = 1; sym2__ <= n_yr; ++sym2__) {
            current_statement__ = 21;
            stan::model::assign(dose_sched, dose_sched_flat__[(pos__ - 1)],
              "assigning variable dose_sched",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 21;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 21;
      stan::math::check_greater_or_equal(function__, "dose_sched",
        dose_sched, 0);
      current_statement__ = 21;
      stan::math::check_less_or_equal(function__, "dose_sched", dose_sched, 1);
      current_statement__ = 22;
      context__.validate_dims("data initialization", "n_obs", "int",
        std::vector<size_t>{});
      n_obs = std::numeric_limits<int>::min();
      current_statement__ = 22;
      n_obs = context__.vals_i("n_obs")[(1 - 1)];
      current_statement__ = 22;
      stan::math::check_greater_or_equal(function__, "n_obs", n_obs, 1);
      current_statement__ = 23;
      stan::math::validate_non_negative_index("y_obs", "n_obs", n_obs);
      current_statement__ = 24;
      context__.validate_dims("data initialization", "y_obs", "int",
        std::vector<size_t>{static_cast<size_t>(n_obs)});
      y_obs = std::vector<int>(n_obs, std::numeric_limits<int>::min());
      current_statement__ = 24;
      y_obs = context__.vals_i("y_obs");
      current_statement__ = 24;
      stan::math::check_greater_or_equal(function__, "y_obs", y_obs, 0);
      current_statement__ = 25;
      stan::math::validate_non_negative_index("y_smp", "n_obs", n_obs);
      current_statement__ = 26;
      context__.validate_dims("data initialization", "y_smp", "int",
        std::vector<size_t>{static_cast<size_t>(n_obs)});
      y_smp = std::vector<int>(n_obs, std::numeric_limits<int>::min());
      current_statement__ = 26;
      y_smp = context__.vals_i("y_smp");
      current_statement__ = 26;
      stan::math::check_greater_or_equal(function__, "y_smp", y_smp, 0);
      current_statement__ = 27;
      context__.validate_dims("data initialization", "n_weights", "int",
        std::vector<size_t>{});
      n_weights = std::numeric_limits<int>::min();
      current_statement__ = 27;
      n_weights = context__.vals_i("n_weights")[(1 - 1)];
      current_statement__ = 27;
      stan::math::check_greater_or_equal(function__, "n_weights", n_weights,
        n_obs);
      current_statement__ = 28;
      stan::math::validate_non_negative_index("obs_to_weights_bounds",
        "n_obs", n_obs);
      current_statement__ = 29;
      context__.validate_dims("data initialization", "obs_to_weights_bounds",
        "int", std::vector<size_t>{static_cast<size_t>(n_obs)});
      obs_to_weights_bounds = std::vector<int>(n_obs,
                                std::numeric_limits<int>::min());
      current_statement__ = 29;
      obs_to_weights_bounds = context__.vals_i("obs_to_weights_bounds");
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "obs_to_weights_bounds",
        obs_to_weights_bounds, 1);
      current_statement__ = 29;
      stan::math::check_less_or_equal(function__, "obs_to_weights_bounds",
        obs_to_weights_bounds, n_weights);
      current_statement__ = 30;
      stan::math::validate_non_negative_index("weights_cohort", "n_weights",
        n_weights);
      current_statement__ = 31;
      context__.validate_dims("data initialization", "weights_cohort", "int",
        std::vector<size_t>{static_cast<size_t>(n_weights)});
      weights_cohort = std::vector<int>(n_weights,
                         std::numeric_limits<int>::min());
      current_statement__ = 31;
      weights_cohort = context__.vals_i("weights_cohort");
      current_statement__ = 31;
      stan::math::check_greater_or_equal(function__, "weights_cohort",
        weights_cohort, 1);
      current_statement__ = 31;
      stan::math::check_less_or_equal(function__, "weights_cohort",
        weights_cohort, n_cohort);
      current_statement__ = 32;
      stan::math::validate_non_negative_index("weights_life_year",
        "n_weights", n_weights);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "weights_life_year",
        "int", std::vector<size_t>{static_cast<size_t>(n_weights)});
      weights_life_year = std::vector<int>(n_weights,
                            std::numeric_limits<int>::min());
      current_statement__ = 33;
      weights_life_year = context__.vals_i("weights_life_year");
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "weights_life_year",
        weights_life_year, 1);
      current_statement__ = 33;
      stan::math::check_less_or_equal(function__, "weights_life_year",
        weights_life_year, n_yr);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("weights_dose", "n_weights",
        n_weights);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "weights_dose", "int",
        std::vector<size_t>{static_cast<size_t>(n_weights)});
      weights_dose = std::vector<int>(n_weights,
                       std::numeric_limits<int>::min());
      current_statement__ = 35;
      weights_dose = context__.vals_i("weights_dose");
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "weights_dose",
        weights_dose, 1);
      current_statement__ = 35;
      stan::math::check_less_or_equal(function__, "weights_dose",
        weights_dose, n_doses);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("weights", "n_weights",
        n_weights);
      current_statement__ = 37;
      context__.validate_dims("data initialization", "weights", "double",
        std::vector<size_t>{static_cast<size_t>(n_weights)});
      weights_data__ = Eigen::Matrix<double,-1,1>::Constant(n_weights,
                         std::numeric_limits<double>::quiet_NaN());
      new (&weights)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(weights_data__.data(),
        n_weights);
      {
        std::vector<local_scalar_t__> weights_flat__;
        current_statement__ = 37;
        weights_flat__ = context__.vals_r("weights");
        current_statement__ = 37;
        pos__ = 1;
        current_statement__ = 37;
        for (int sym1__ = 1; sym1__ <= n_weights; ++sym1__) {
          current_statement__ = 37;
          stan::model::assign(weights, weights_flat__[(pos__ - 1)],
            "assigning variable weights", stan::model::index_uni(sym1__));
          current_statement__ = 37;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 37;
      stan::math::check_greater_or_equal(function__, "weights", weights, 0);
      current_statement__ = 37;
      stan::math::check_less_or_equal(function__, "weights", weights, 1);
      current_statement__ = 38;
      context__.validate_dims("data initialization", "predict_mode", "int",
        std::vector<size_t>{});
      predict_mode = std::numeric_limits<int>::min();
      current_statement__ = 38;
      predict_mode = context__.vals_i("predict_mode")[(1 - 1)];
      current_statement__ = 38;
      stan::math::check_greater_or_equal(function__, "predict_mode",
        predict_mode, 0);
      current_statement__ = 38;
      stan::math::check_less_or_equal(function__, "predict_mode",
        predict_mode, 1);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "k_bs", "int",
        std::vector<size_t>{});
      k_bs = std::numeric_limits<int>::min();
      current_statement__ = 39;
      k_bs = context__.vals_i("k_bs")[(1 - 1)];
      current_statement__ = 40;
      stan::math::validate_non_negative_index("bs", "n_cohort", n_cohort);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("bs", "k_bs", k_bs);
      current_statement__ = 42;
      context__.validate_dims("data initialization", "bs", "double",
        std::vector<size_t>{static_cast<size_t>(n_cohort),
          static_cast<size_t>(k_bs)});
      bs_data__ = Eigen::Matrix<double,-1,-1>::Constant(n_cohort, k_bs,
                    std::numeric_limits<double>::quiet_NaN());
      new (&bs) Eigen::Map<Eigen::Matrix<double,-1,-1>>(bs_data__.data(),
        n_cohort, k_bs);
      {
        std::vector<local_scalar_t__> bs_flat__;
        current_statement__ = 42;
        bs_flat__ = context__.vals_r("bs");
        current_statement__ = 42;
        pos__ = 1;
        current_statement__ = 42;
        for (int sym1__ = 1; sym1__ <= k_bs; ++sym1__) {
          current_statement__ = 42;
          for (int sym2__ = 1; sym2__ <= n_cohort; ++sym2__) {
            current_statement__ = 42;
            stan::model::assign(bs, bs_flat__[(pos__ - 1)],
              "assigning variable bs", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 42;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 43;
      stan::math::validate_non_negative_index("obs_map", "n_obs", n_obs);
      current_statement__ = 44;
      obs_map = std::vector<std::vector<int>>(2,
                  std::vector<int>(n_obs, std::numeric_limits<int>::min()));
      current_statement__ = 44;
      stan::model::assign(obs_map,
        bounds_to_range(obs_to_weights_bounds, n_weights, pstream__),
        "assigning variable obs_map");
      current_statement__ = 45;
      stan::math::validate_non_negative_index("phi_lookup", "n_weights",
        n_weights);
      current_statement__ = 46;
      phi_lookup = std::vector<int>(n_weights,
                     std::numeric_limits<int>::min());
      current_statement__ = 47;
      stan::math::validate_non_negative_index("cdf_lookup", "n_weights",
        n_weights);
      current_statement__ = 48;
      cdf_lookup = std::vector<int>(n_weights,
                     std::numeric_limits<int>::min());
      current_statement__ = 52;
      for (int weight_i = 1; weight_i <= n_weights; ++weight_i) {
        current_statement__ = 49;
        stan::model::assign(phi_lookup,
          stan::model::rvalue(weights_cohort, "weights_cohort",
            stan::model::index_uni(weight_i)),
          "assigning variable phi_lookup", stan::model::index_uni(weight_i));
        current_statement__ = 50;
        stan::model::assign(cdf_lookup,
          (stan::model::rvalue(weights_life_year, "weights_life_year",
             stan::model::index_uni(weight_i)) +
          ((stan::model::rvalue(weights_dose, "weights_dose",
              stan::model::index_uni(weight_i)) - 1) * n_yr)),
          "assigning variable cdf_lookup", stan::model::index_uni(weight_i));
      }
      current_statement__ = 53;
      epsilon_p = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 53;
      epsilon_p = 1e-10;
      current_statement__ = 46;
      stan::math::check_greater_or_equal(function__, "phi_lookup",
        phi_lookup, 1);
      current_statement__ = 48;
      stan::math::check_greater_or_equal(function__, "cdf_lookup",
        cdf_lookup, 1);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("beta_bs", "k_bs", k_bs);
      current_statement__ = 55;
      stan::math::validate_non_negative_index("lambda_raw", "n_doses",
        n_doses);
      current_statement__ = 56;
      stan::math::validate_non_negative_index("logit_phi_st", "n_cohort",
        n_cohort);
      current_statement__ = 57;
      stan::math::validate_non_negative_index("phi", "n_cohort", n_cohort);
      current_statement__ = 58;
      unrolled_dose_probs_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 58;
      unrolled_dose_probs_1dim__ = (n_doses * n_yr);
      current_statement__ = 58;
      stan::math::validate_non_negative_index("unrolled_dose_probs",
        "n_doses * n_yr", unrolled_dose_probs_1dim__);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("weighted", "n_weights",
        n_weights);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("p_obs", "n_obs", n_obs);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = k_bs + n_doses;
  }
  inline std::string model_name() const final {
    return "model_impute_school_coverage_process_stateonly";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_impute_school_coverage_process_stateonly_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> beta_bs =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(k_bs, DUMMY_VAR__);
      current_statement__ = 1;
      beta_bs = in__.template read<
                  Eigen::Matrix<local_scalar_t__,-1,1>>(k_bs);
      Eigen::Matrix<local_scalar_t__,-1,1> lambda_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_doses, DUMMY_VAR__);
      current_statement__ = 2;
      lambda_raw = in__.template read<
                     Eigen::Matrix<local_scalar_t__,-1,1>>(n_doses);
      Eigen::Matrix<local_scalar_t__,-1,1> logit_phi_st =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_cohort, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(logit_phi_st, stan::math::multiply(bs, beta_bs),
        "assigning variable logit_phi_st");
      Eigen::Matrix<local_scalar_t__,-1,1> phi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_cohort, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(phi, stan::math::inv_logit(logit_phi_st),
        "assigning variable phi");
      Eigen::Matrix<local_scalar_t__,-1,1> unrolled_dose_probs =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(unrolled_dose_probs_1dim__,
          DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(unrolled_dose_probs,
        unrolled_dose(n_yr, n_doses, dose_sched, lambda_raw, epsilon_p,
          pstream__), "assigning variable unrolled_dose_probs");
      Eigen::Matrix<local_scalar_t__,-1,1> weighted =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_weights,
          DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(weighted,
        stan::math::elt_multiply(
          stan::math::elt_multiply(
            stan::math::subtract(1,
              stan::model::rvalue(phi, "phi",
                stan::model::index_multi(phi_lookup))),
            stan::model::rvalue(unrolled_dose_probs, "unrolled_dose_probs",
              stan::model::index_multi(cdf_lookup))), weights),
        "assigning variable weighted");
      Eigen::Matrix<local_scalar_t__,-1,1> p_obs =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_obs, DUMMY_VAR__);
      current_statement__ = 10;
      for (int obs_i = 1; obs_i <= n_obs; ++obs_i) {
        current_statement__ = 8;
        stan::model::assign(p_obs,
          stan::math::sum(
            stan::model::rvalue(weighted, "weighted",
              stan::model::index_min_max(
                stan::model::rvalue(obs_map, "obs_map",
                  stan::model::index_uni(1), stan::model::index_uni(obs_i)),
                stan::model::rvalue(obs_map, "obs_map",
                  stan::model::index_uni(2), stan::model::index_uni(obs_i))))),
          "assigning variable p_obs", stan::model::index_uni(obs_i));
      }
      current_statement__ = 5;
      stan::math::check_greater_or_equal(function__, "unrolled_dose_probs",
        unrolled_dose_probs, 0);
      current_statement__ = 5;
      stan::math::check_less_or_equal(function__, "unrolled_dose_probs",
        unrolled_dose_probs, 1);
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "weighted", weighted, 0);
      current_statement__ = 6;
      stan::math::check_less_or_equal(function__, "weighted", weighted, 1);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "p_obs", p_obs, 0);
      current_statement__ = 7;
      stan::math::check_less_or_equal(function__, "p_obs", p_obs, 1);
      {
        current_statement__ = 15;
        if (stan::math::logical_negation(predict_mode)) {
          current_statement__ = 11;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_bs, 0, 10));
          current_statement__ = 12;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(lambda_raw,
                           stan::math::log(3), 1));
          current_statement__ = 13;
          lp_accum__.add(stan::math::binomial_lpmf<propto__>(y_obs, y_smp,
                           p_obs));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_impute_school_coverage_process_stateonly_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> beta_bs =
        Eigen::Matrix<double,-1,1>::Constant(k_bs,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      beta_bs = in__.template read<
                  Eigen::Matrix<local_scalar_t__,-1,1>>(k_bs);
      Eigen::Matrix<double,-1,1> lambda_raw =
        Eigen::Matrix<double,-1,1>::Constant(n_doses,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      lambda_raw = in__.template read<
                     Eigen::Matrix<local_scalar_t__,-1,1>>(n_doses);
      Eigen::Matrix<double,-1,1> logit_phi_st =
        Eigen::Matrix<double,-1,1>::Constant(n_cohort,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> phi =
        Eigen::Matrix<double,-1,1>::Constant(n_cohort,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> unrolled_dose_probs =
        Eigen::Matrix<double,-1,1>::Constant(unrolled_dose_probs_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> weighted =
        Eigen::Matrix<double,-1,1>::Constant(n_weights,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> p_obs =
        Eigen::Matrix<double,-1,1>::Constant(n_obs,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(beta_bs);
      out__.write(lambda_raw);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 3;
      stan::model::assign(logit_phi_st, stan::math::multiply(bs, beta_bs),
        "assigning variable logit_phi_st");
      current_statement__ = 4;
      stan::model::assign(phi, stan::math::inv_logit(logit_phi_st),
        "assigning variable phi");
      current_statement__ = 5;
      stan::model::assign(unrolled_dose_probs,
        unrolled_dose(n_yr, n_doses, dose_sched, lambda_raw, epsilon_p,
          pstream__), "assigning variable unrolled_dose_probs");
      current_statement__ = 6;
      stan::model::assign(weighted,
        stan::math::elt_multiply(
          stan::math::elt_multiply(
            stan::math::subtract(1,
              stan::model::rvalue(phi, "phi",
                stan::model::index_multi(phi_lookup))),
            stan::model::rvalue(unrolled_dose_probs, "unrolled_dose_probs",
              stan::model::index_multi(cdf_lookup))), weights),
        "assigning variable weighted");
      current_statement__ = 10;
      for (int obs_i = 1; obs_i <= n_obs; ++obs_i) {
        current_statement__ = 8;
        stan::model::assign(p_obs,
          stan::math::sum(
            stan::model::rvalue(weighted, "weighted",
              stan::model::index_min_max(
                stan::model::rvalue(obs_map, "obs_map",
                  stan::model::index_uni(1), stan::model::index_uni(obs_i)),
                stan::model::rvalue(obs_map, "obs_map",
                  stan::model::index_uni(2), stan::model::index_uni(obs_i))))),
          "assigning variable p_obs", stan::model::index_uni(obs_i));
      }
      current_statement__ = 5;
      stan::math::check_greater_or_equal(function__, "unrolled_dose_probs",
        unrolled_dose_probs, 0);
      current_statement__ = 5;
      stan::math::check_less_or_equal(function__, "unrolled_dose_probs",
        unrolled_dose_probs, 1);
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "weighted", weighted, 0);
      current_statement__ = 6;
      stan::math::check_less_or_equal(function__, "weighted", weighted, 1);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "p_obs", p_obs, 0);
      current_statement__ = 7;
      stan::math::check_less_or_equal(function__, "p_obs", p_obs, 1);
      if (emit_transformed_parameters__) {
        out__.write(logit_phi_st);
        out__.write(phi);
        out__.write(unrolled_dose_probs);
        out__.write(weighted);
        out__.write(p_obs);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta_bs =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(k_bs, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(beta_bs,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(k_bs),
        "assigning variable beta_bs");
      out__.write(beta_bs);
      Eigen::Matrix<local_scalar_t__,-1,1> lambda_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_doses, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(lambda_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(n_doses),
        "assigning variable lambda_raw");
      out__.write(lambda_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "beta_bs",
        "double", std::vector<size_t>{static_cast<size_t>(k_bs)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "lambda_raw",
        "double", std::vector<size_t>{static_cast<size_t>(n_doses)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta_bs =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(k_bs, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_bs_flat__;
        current_statement__ = 1;
        beta_bs_flat__ = context__.vals_r("beta_bs");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= k_bs; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(beta_bs, beta_bs_flat__[(pos__ - 1)],
            "assigning variable beta_bs", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta_bs);
      Eigen::Matrix<local_scalar_t__,-1,1> lambda_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_doses, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> lambda_raw_flat__;
        current_statement__ = 2;
        lambda_raw_flat__ = context__.vals_r("lambda_raw");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= n_doses; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(lambda_raw, lambda_raw_flat__[(pos__ - 1)],
            "assigning variable lambda_raw", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(lambda_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"beta_bs", "lambda_raw"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"logit_phi_st", "phi", "unrolled_dose_probs", "weighted",
             "p_obs"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    k_bs)},
                std::vector<size_t>{static_cast<size_t>(n_doses)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(n_cohort)},
             std::vector<size_t>{static_cast<size_t>(n_cohort)},
             std::vector<size_t>{static_cast<size_t>(
                                   unrolled_dose_probs_1dim__)},
             std::vector<size_t>{static_cast<size_t>(n_weights)},
             std::vector<size_t>{static_cast<size_t>(n_obs)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= k_bs; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_bs" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= n_doses; ++sym1__) {
      param_names__.emplace_back(std::string() + "lambda_raw" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n_cohort; ++sym1__) {
        param_names__.emplace_back(std::string() + "logit_phi_st" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_cohort; ++sym1__) {
        param_names__.emplace_back(std::string() + "phi" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= unrolled_dose_probs_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "unrolled_dose_probs" +
          '.' + std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_weights; ++sym1__) {
        param_names__.emplace_back(std::string() + "weighted" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "p_obs" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= k_bs; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_bs" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= n_doses; ++sym1__) {
      param_names__.emplace_back(std::string() + "lambda_raw" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n_cohort; ++sym1__) {
        param_names__.emplace_back(std::string() + "logit_phi_st" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_cohort; ++sym1__) {
        param_names__.emplace_back(std::string() + "phi" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= unrolled_dose_probs_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "unrolled_dose_probs" +
          '.' + std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_weights; ++sym1__) {
        param_names__.emplace_back(std::string() + "weighted" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "p_obs" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta_bs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(k_bs) + "},\"block\":\"parameters\"},{\"name\":\"lambda_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_doses) + "},\"block\":\"parameters\"},{\"name\":\"logit_phi_st\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_cohort) + "},\"block\":\"transformed_parameters\"},{\"name\":\"phi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_cohort) + "},\"block\":\"transformed_parameters\"},{\"name\":\"unrolled_dose_probs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(unrolled_dose_probs_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"weighted\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_weights) + "},\"block\":\"transformed_parameters\"},{\"name\":\"p_obs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_obs) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta_bs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(k_bs) + "},\"block\":\"parameters\"},{\"name\":\"lambda_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_doses) + "},\"block\":\"parameters\"},{\"name\":\"logit_phi_st\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_cohort) + "},\"block\":\"transformed_parameters\"},{\"name\":\"phi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_cohort) + "},\"block\":\"transformed_parameters\"},{\"name\":\"unrolled_dose_probs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(unrolled_dose_probs_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"weighted\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_weights) + "},\"block\":\"transformed_parameters\"},{\"name\":\"p_obs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_obs) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (k_bs + n_doses);
    const size_t num_transformed = emit_transformed_parameters *
      (((((n_cohort + n_cohort) + unrolled_dose_probs_1dim__) + n_weights) +
      n_obs));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (k_bs + n_doses);
    const size_t num_transformed = emit_transformed_parameters *
      (((((n_cohort + n_cohort) + unrolled_dose_probs_1dim__) + n_weights) +
      n_obs));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_impute_school_coverage_process_stateonly_namespace::model_impute_school_coverage_process_stateonly;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_impute_school_coverage_process_stateonly_namespace::profiles__;
}
#endif
#endif
