# Generated by flexstanr 0.2.0: do not edit by hand.
# Regenerate with flexstanr::use_flexstanr() (updates DESCRIPTION and this file).
#
# flexstanr provides this package's portable Stan backend: the backend-agnostic
# fit / draws / generated-quantities entry points and the sampler-option
# constructor, resolving this package's compiled stanmodels automatically. The
# fit_model()/backend_* entry points are imported for internal use; only the
# constructor(s) below are re-exported as part of this package's public API.

#' @importFrom flexstanr fit_model backend_draws_array backend_extract
#' @importFrom flexstanr backend_generate_quantities backend_has_draws
NULL

#' @importFrom flexstanr stan_options
#' @export
flexstanr::stan_options
