# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  ".", # <canonicalize_locations>
  "parent_id", # <canonicalize_locations>
  "id", # <canonicalize_locations>
  "layer", # <canonicalize_locations>
  "c_id", # <canonicalize_locations>
  "cp_id", # <canonicalize_locations>
  "id", # <canonicalize_observations>
  "positive", # <canonicalize_observations>
  "sample_n", # <canonicalize_observations>
  "censored", # <canonicalize_observations>
  "obs_id", # <canonicalize_observations>
  "layer", # <imuGAP>
  "N", # <imuGAP>
  "cohort", # <imuGAP>
  "censored", # <imuGAP>
  "layer_bound", # <imuGAP>
  NULL
))
