# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  ".", # <canonicalize_locations>
  "parent_id", # <canonicalize_locations>
  "id", # <canonicalize_locations>
  "layer", # <canonicalize_locations>
  "c_id", # <canonicalize_locations>
  "cp_id", # <canonicalize_locations>
  "layer_bound", # <canonicalize_locations>
  "id", # <canonicalize_observations>
  "positive", # <canonicalize_observations>
  "sample_n", # <canonicalize_observations>
  "censored", # <canonicalize_observations>
  "c_id", # <canonicalize_observations>
  "weight", # <canonicalize_populations>
  "obs_id", # <canonicalize_populations>
  "id", # <canonicalize_populations>
  "obs_c_id", # <canonicalize_populations>
  "c_id", # <canonicalize_populations>
  "loc_c_id", # <canonicalize_populations>
  "cohort", # <canonicalize_populations>
  "age", # <canonicalize_populations>
  "dose", # <canonicalize_populations>
  "range_start", # <canonicalize_populations>
  "layer", # <imuGAP>
  "N", # <imuGAP>
  "cohort", # <imuGAP>
  "censored", # <imuGAP>
  "layer_bound", # <imuGAP>
  NULL
))
